---
- name: Config Git user
  git_config:
    name: user.name
    scope: global  
    value: "{{ git_user }}"

- name: Config Git Email
  git_config:
    name: user.email
    scope: global  
    value: "{{ git_email }}"

- name: Install MacVim
  command: "brew tap homebrew/cask-fonts"

- name: Install Hack Nerd Font
  community.general.homebrew_cask:
    name: font-hack-nerd-font
    state: present  

- name: Install MacVim
  community.general.homebrew:
    name: macvim
    state: present  

- name: Install vim-plug
  command: "curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

- name: Install gitui
  community.general.homebrew:
    name: gitui
    state: present  

- name: Install JetBrains Toolbox
  community.general.homebrew_cask:
    name: jetbrains-toolbox
    state: present  

- block: 
  - name: "Install docker : Check existing installation"
    shell: "which docker"
    failed_when: false
    register: which_docker
    changed_when: false

  - name: "Install docker : Install via homebrew cask"
    when: which_docker.rc != 0
    community.general.homebrew_cask:
      name: docker
      state: present  
