---
- name: Install Fastlane
  community.general.homebrew:
    name: fastlane
    state: upgraded

- name: Install SDKMAN
  ansible.builtin.shell: |
    curl -s "https://get.sdkman.io" | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install java {{ jdk }}
