---
- gather_facts: no
  hosts: all
  vars:
    ansible_remote_tmp: /tmp
    git_user: "Seaborn Lee"
    git_email: "seabornlee.cn@gmail.com"
    dotfiles_repo: "seabornlee/yadm-dotfiles"
    jdk: "11.0.15-zulu"
  pre_tasks:
    - name: "Ensure current user has admin privileges"
      ansible.builtin.shell:
        cmd: 'groups | grep -q -w admin'
      changed_when: false
    - name: "Ensure user is not running as root"
      ansible.builtin.shell:
        cmd: '[[ "$(whoami)" != "root" ]] || exit 1'
      changed_when: false
    - name: "Ensure sudo password is provided"
      become: true
      ansible.builtin.shell:
        cmd: '[[ "$(whoami)" == "root" ]] || exit 1'
      changed_when: false      
  roles:
    - poweruser
    - android-developer
    - cli
    - any-developer
    - dotfiles
    - daily
